HozuniCity_House3_MapScripts::
	.byte 0

HozuniCity_House3_EventScript_GameboyKid::
	msgbox HozuniCity_House3_Text_GameboyKid, MSGBOX_NPC
	end

HozuniCity_House3_EventScript_Woman::
	msgbox HozuniCity_House3_Text_Woman, MSGBOX_NPC
	end

HozuniCity_House3_Text_Woman:
	.string "My son is always watching POKéMON\n"
	.string "BATTLES on TV. I wish he'd go outside\l"
	.string "and experience the real thing!$"


HozuniCity_House3_Text_GameboyKid:
	.string "Shhh! I'm trying to watch TV!$"
