Common_EventScript_FindItem::
	callnative GetItemBallIdAndAmountFromTemplate
	finditem VAR_RESULT VAR_0x8009
	end

TobaachiTown_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

TobaachiTown_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

TobaachiTown_EventScript_ItemGreat_Ball::
	finditem ITEM_GREAT_BALL
	end

TobaachiTown_EventScript_ItemPP_Up::
	finditem ITEM_PP_UP
	end

HozuniCity_EventScript_Debug_EggCoupon::
	finditem ITEM_EGG_COUPON
	end
