HozuniCity_House1_MapScripts::
	.byte 0

HozuniCity_House1_EventScript_Woman1::
	msgbox HozuniCity_House1_Text_Woman1, MSGBOX_NPC
	end

HozuniCity_House1_EventScript_Woman2::
	msgbox HozuniCity_House1_Text_Woman2, MSGBOX_NPC
	end
	
HozuniCity_House1_Text_Woman1:
	.string "HOZUNI CITY is famous for its ancient\n"
	.string "relics.\p"
	.string "If you investigate some of them, you\n"
	.string "might find something inside!$"

HozuniCity_House1_Text_Woman2:
	.string "Have you been to the TRAINER SCHOOL\n"
	.string "in HOZUNI CITY yet?\p"
	.string "I heard they teach lessons to new\n"
	.string "trainers!$"